//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iagric_plant.ServiceJK {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/", ConfigurationName="ServiceJK.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: 命名空间 http://localhost/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/HelloWorld", ReplyAction="*")]
        iagric_plant.ServiceJK.HelloWorldResponse HelloWorld(iagric_plant.ServiceJK.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://localhost/ 的元素名称 traceCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost/GetEnterpriseMainCode", ReplyAction="*")]
        iagric_plant.ServiceJK.GetEnterpriseMainCodeResponse GetEnterpriseMainCode(iagric_plant.ServiceJK.GetEnterpriseMainCodeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://localhost/", Order=0)]
        public iagric_plant.ServiceJK.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(iagric_plant.ServiceJK.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://localhost/", Order=0)]
        public iagric_plant.ServiceJK.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(iagric_plant.ServiceJK.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEnterpriseMainCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEnterpriseMainCode", Namespace="http://localhost/", Order=0)]
        public iagric_plant.ServiceJK.GetEnterpriseMainCodeRequestBody Body;
        
        public GetEnterpriseMainCodeRequest() {
        }
        
        public GetEnterpriseMainCodeRequest(iagric_plant.ServiceJK.GetEnterpriseMainCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class GetEnterpriseMainCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string traceCode;
        
        public GetEnterpriseMainCodeRequestBody() {
        }
        
        public GetEnterpriseMainCodeRequestBody(string traceCode) {
            this.traceCode = traceCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEnterpriseMainCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEnterpriseMainCodeResponse", Namespace="http://localhost/", Order=0)]
        public iagric_plant.ServiceJK.GetEnterpriseMainCodeResponseBody Body;
        
        public GetEnterpriseMainCodeResponse() {
        }
        
        public GetEnterpriseMainCodeResponse(iagric_plant.ServiceJK.GetEnterpriseMainCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost/")]
    public partial class GetEnterpriseMainCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetEnterpriseMainCodeResult;
        
        public GetEnterpriseMainCodeResponseBody() {
        }
        
        public GetEnterpriseMainCodeResponseBody(string GetEnterpriseMainCodeResult) {
            this.GetEnterpriseMainCodeResult = GetEnterpriseMainCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : iagric_plant.ServiceJK.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<iagric_plant.ServiceJK.WebService1Soap>, iagric_plant.ServiceJK.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iagric_plant.ServiceJK.HelloWorldResponse iagric_plant.ServiceJK.WebService1Soap.HelloWorld(iagric_plant.ServiceJK.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            iagric_plant.ServiceJK.HelloWorldRequest inValue = new iagric_plant.ServiceJK.HelloWorldRequest();
            inValue.Body = new iagric_plant.ServiceJK.HelloWorldRequestBody();
            iagric_plant.ServiceJK.HelloWorldResponse retVal = ((iagric_plant.ServiceJK.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        iagric_plant.ServiceJK.GetEnterpriseMainCodeResponse iagric_plant.ServiceJK.WebService1Soap.GetEnterpriseMainCode(iagric_plant.ServiceJK.GetEnterpriseMainCodeRequest request) {
            return base.Channel.GetEnterpriseMainCode(request);
        }
        
        public string GetEnterpriseMainCode(string traceCode) {
            iagric_plant.ServiceJK.GetEnterpriseMainCodeRequest inValue = new iagric_plant.ServiceJK.GetEnterpriseMainCodeRequest();
            inValue.Body = new iagric_plant.ServiceJK.GetEnterpriseMainCodeRequestBody();
            inValue.Body.traceCode = traceCode;
            iagric_plant.ServiceJK.GetEnterpriseMainCodeResponse retVal = ((iagric_plant.ServiceJK.WebService1Soap)(this)).GetEnterpriseMainCode(inValue);
            return retVal.Body.GetEnterpriseMainCodeResult;
        }
    }
}
