//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinqModel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.44;Initial Catalog=FWZSNyWebNew;Persist Security Info=True;" +
            "User ID=sa")]
        public string FWZSNyWebNewConnectionString {
            get {
                return ((string)(this["FWZSNyWebNewConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=WineShow;Persist Security Info=True;User " +
            "ID=gl_ny")]
        public string AgricWebConnectionString {
            get {
                return ((string)(this["AgricWebConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=AgricWeb;Persist Security Info=True;User " +
            "ID=gl_tester")]
        public string AgricWebConnectionString1 {
            get {
                return ((string)(this["AgricWebConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=AgricWeb;User ID=gl_ny")]
        public string AgricWebConnectionString3 {
            get {
                return ((string)(this["AgricWebConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=Agric_Code;Persist Security Info=True;Use" +
            "r ID=gl_ny")]
        public string AgricWebConnectionString2 {
            get {
                return ((string)(this["AgricWebConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=Agric_Code;Persist Security Info=True;Use" +
            "r ID=gl_ny")]
        public string Agric_CodeConnectionString {
            get {
                return ((string)(this["Agric_CodeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=AgricWeb;Persist Security Info=True;User " +
            "ID=gl_tester")]
        public string AgricWebConnectionString4 {
            get {
                return ((string)(this["AgricWebConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=AgricShow;User ID=gl_ny")]
        public string AgricShowConnectionString {
            get {
                return ((string)(this["AgricShowConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=AgricWeb;Persist Security Info=True;User " +
            "ID=gl_tester")]
        public string AgricWebConnectionString5 {
            get {
                return ((string)(this["AgricWebConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=AgricShow;Persist Security Info=True;User" +
            " ID=gl_ny")]
        public string AgricShowConnectionString1 {
            get {
                return ((string)(this["AgricShowConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=AgricWeb;User ID=gl_ny;Password=jsyb12345" +
            "6")]
        public string AgricWebConnectionString6 {
            get {
                return ((string)(this["AgricWebConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=AgricWeb;Persist Security Info=True;User " +
            "ID=gl_tester")]
        public string AgricWebConnectionString7 {
            get {
                return ((string)(this["AgricWebConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=AgricWeb;Persist Security Info=True;User " +
            "ID=gl_cllyt")]
        public string AgricWebConnectionString8 {
            get {
                return ((string)(this["AgricWebConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=WineShow;Persist Security Info=True;User " +
            "ID=gl_ny")]
        public string WineShowConnectionString {
            get {
                return ((string)(this["WineShowConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=WineWeb;Persist Security Info=True;User I" +
            "D=gl_tester")]
        public string WineWebConnectionString {
            get {
                return ((string)(this["WineWebConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=Wine_Code;Persist Security Info=True;User" +
            " ID=gl_ny")]
        public string Wine_CodeConnectionString {
            get {
                return ((string)(this["Wine_CodeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=Wine_Code;User ID=gl_ny")]
        public string Wine_CodeConnectionString1 {
            get {
                return ((string)(this["Wine_CodeConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=WineWeb;Persist Security Info=True;User I" +
            "D=gl_ny")]
        public string WineWebConnectionString1 {
            get {
                return ((string)(this["WineWebConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=WineWeb;User ID=gl_ny")]
        public string WineWebConnectionString2 {
            get {
                return ((string)(this["WineWebConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.40;Initial Catalog=AgricWeb;Persist Security Info=True;User" +
            " ID=sa")]
        public string AgricWebConnectionString9 {
            get {
                return ((string)(this["AgricWebConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=Agric_Code;User ID=gl_ny")]
        public string Agric_CodeConnectionString1 {
            get {
                return ((string)(this["Agric_CodeConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.40;Initial Catalog=Agric_Code;Persist Security Info=True;Us" +
            "er ID=sa")]
        public string Agric_CodeConnectionString2 {
            get {
                return ((string)(this["Agric_CodeConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.40;Initial Catalog=AgricWeb;Persist Security Info=True;User" +
            " ID=sa;Password=123456")]
        public string AgricWebConnectionString10 {
            get {
                return ((string)(this["AgricWebConnectionString10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.40;Initial Catalog=Agric_Code;User ID=sa")]
        public string Agric_CodeConnectionString3 {
            get {
                return ((string)(this["Agric_CodeConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=AgricWeb;Persist Security Info=True;User " +
            "ID=gl_tester")]
        public string AgricWebConnectionString11 {
            get {
                return ((string)(this["AgricWebConnectionString11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=AgricWeb;User ID=gl_ny")]
        public string AgricWebConnectionString12 {
            get {
                return ((string)(this["AgricWebConnectionString12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=AgricWeb;Persist Security Info=True;User " +
            "ID=gl_ny")]
        public string AgricWebConnectionString13 {
            get {
                return ((string)(this["AgricWebConnectionString13"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=AgricWeb;Persist Security Info=True;User " +
            "ID=gl_tester;Password=zjb123")]
        public string AgricWebConnectionString14 {
            get {
                return ((string)(this["AgricWebConnectionString14"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=AgricWeb;Persist Security Info=True;User " +
            "ID=gl_ny;Password=jsyb123456")]
        public string AgricWebConnectionString15 {
            get {
                return ((string)(this["AgricWebConnectionString15"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=NewMeatTraceWeb;Persist Security Info=Tru" +
            "e;User ID=gl_ny;Password=jsyb123456")]
        public string NewMeatTraceWebConnectionString {
            get {
                return ((string)(this["NewMeatTraceWebConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=NewMeatTraceWeb;Persist Security Info=Tru" +
            "e;User ID=gl_ny;Password=jsyb123456")]
        public string NewMeatTraceWebConnectionString1 {
            get {
                return ((string)(this["NewMeatTraceWebConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=123.56.91.27;Initial Catalog=NewMeatTraceWeb;User ID=nmctest")]
        public string NewMeatTraceWebConnectionString2 {
            get {
                return ((string)(this["NewMeatTraceWebConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=TracePublicData;Persist Security Info=True;User ID=" +
            "sa")]
        public string ImpTraceWebConnectionString8 {
            get {
                return ((string)(this["ImpTraceWebConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=TracePublicData;Persist Security Info=True;User ID=" +
            "sa")]
        public string TracePublicDataConnectionString {
            get {
                return ((string)(this["TracePublicDataConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.227;Initial Catalog=ImpTrace_Code;User ID=gl_ny")]
        public string ImpTrace_CodeConnectionString {
            get {
                return ((string)(this["ImpTrace_CodeConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.227;Initial Catalog=ShamoTraceWeb;User ID=gl_ny")]
        public string ShamoTraceWebConnectionString {
            get {
                return ((string)(this["ShamoTraceWebConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=YiLiaoWeb;Persist Security Info=True;User" +
            " ID=gl_ny;Password=jsyb123456")]
        public string ImpTraceWebConnectionString {
            get {
                return ((string)(this["ImpTraceWebConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=YiLiaoWeb;User ID=gl_ny;Password=jsyb1234" +
            "56")]
        public string ImpTraceWebConnectionString1 {
            get {
                return ((string)(this["ImpTraceWebConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=YiLiaoWeb;Persist Security Info=True;User" +
            " ID=gl_ny;Password=jsyb123456")]
        public string ImpTraceWebConnectionString2 {
            get {
                return ((string)(this["ImpTraceWebConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=123.56.91.27;Initial Catalog=YiLiaoWeb;User ID=gl")]
        public string ImpTraceWebConnectionString3 {
            get {
                return ((string)(this["ImpTraceWebConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=YiLiaoWeb;User ID=gl_ny")]
        public string ImpTraceWebConnectionString4 {
            get {
                return ((string)(this["ImpTraceWebConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=YiLiaoWeb;Persist Security Info=True;User" +
            " ID=gl_tester")]
        public string ImpTraceWebConnectionString5 {
            get {
                return ((string)(this["ImpTraceWebConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.7;Initial Catalog=YiLiaoWeb;Persist Security Info=True;User" +
            " ID=gl_tester;Password=zjb123")]
        public string ImpTraceWebConnectionString6 {
            get {
                return ((string)(this["ImpTraceWebConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.227;Initial Catalog=YiLiaoWeb;User ID=gl_ny")]
        public string ImpTraceWebConnectionString7 {
            get {
                return ((string)(this["ImpTraceWebConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.227;Initial Catalog=YiLiaoWeb;User ID=gl_ny")]
        public string ImpTraceWebConnectionString9 {
            get {
                return ((string)(this["ImpTraceWebConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=121.28.25.114;Initial Catalog=YiLiaoWeb;Persist Security Info=True;Us" +
            "er ID=gl_ny")]
        public string ImpTraceWebConnectionString10 {
            get {
                return ((string)(this["ImpTraceWebConnectionString10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.47;Initial Catalog=YiLiaoWeb;User ID=sa")]
        public string ImpTraceWebConnectionString11 {
            get {
                return ((string)(this["ImpTraceWebConnectionString11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=YiLiaoWeb;Persist Security Info=True;User ID=sa")]
        public string ImpTraceWebConnectionString12 {
            get {
                return ((string)(this["ImpTraceWebConnectionString12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=121.28.25.114;Initial Catalog=YiLiaoWeb;User ID=gl_ny")]
        public string YiLiaoWebConnectionString {
            get {
                return ((string)(this["YiLiaoWebConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=121.28.25.114;Initial Catalog=YiLiaoWeb;Persist Security Info=True;Us" +
            "er ID=gl_ny;Password=jsyb123456")]
        public string YiLiaoWebConnectionString1 {
            get {
                return ((string)(this["YiLiaoWebConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.227;Initial Catalog=YiLiaoWeb;User ID=gl_ny")]
        public string YiLiaoWebConnectionString2 {
            get {
                return ((string)(this["YiLiaoWebConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.47;Initial Catalog=YiLiaoWeb;User ID=sa")]
        public string YiLiaoWebConnectionString3 {
            get {
                return ((string)(this["YiLiaoWebConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.47;Initial Catalog=YiLiaoWeb;User ID=sa")]
        public string YiLiaoWebConnectionString4 {
            get {
                return ((string)(this["YiLiaoWebConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.47;Initial Catalog=YiLiaoWeb;Persist Security Info=True;Use" +
            "r ID=sa")]
        public string YiLiaoWebConnectionString5 {
            get {
                return ((string)(this["YiLiaoWebConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.227;Initial Catalog=YiLiaoWeb;Persist Security Info=True;Us" +
            "er ID=gl_ny")]
        public string YiLiaoWebConnectionString6 {
            get {
                return ((string)(this["YiLiaoWebConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=YiLiaoWeb;User ID=sa")]
        public string YiLiaoWebConnectionString7 {
            get {
                return ((string)(this["YiLiaoWebConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.;Initial Catalog=YiLiaoWeb;Persist Security Info=True;User ID=sa;Pas" +
            "sword=123456")]
        public string YiLiaoWebConnectionString8 {
            get {
                return ((string)(this["YiLiaoWebConnectionString8"]));
            }
        }
    }
}
